[package]
name = "raymarcher"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
glam = "0.27.0"
image = { version = "0.25.1", default-features = false, features = ["png"] }
rand = "0.8.5"
